import { CategoryDefinition } from '../engine/types';

export const basicCategories: CategoryDefinition[] = [
  {
    id: 'length',
    name: 'Length & Distance',
    group: 'Basic',
    iconName: 'Ruler',
    description: 'Convert between metric, imperial, astronomical, and nautical distance units.',
    baseUnitId: 'meter',
    popularPairs: [
      ['kilometer', 'mile'],
      ['meter', 'foot'],
      ['centimeter', 'inch'],
      ['millimeter', 'inch'],
      ['yard', 'meter'],
    ],
    units: [
      { id: 'meter', name: 'Meter', symbol: 'm', category: 'length', factor: 1, baseUnit: true, system: 'si', aliases: ['meter', 'meters', 'metre', 'metres', 'm'] },
      { id: 'kilometer', name: 'Kilometer', symbol: 'km', category: 'length', factor: 1000, system: 'metric', aliases: ['kilometer', 'kilometers', 'kilometre', 'kilometres', 'km', 'kms'] },
      { id: 'centimeter', name: 'Centimeter', symbol: 'cm', category: 'length', factor: 0.01, system: 'metric', aliases: ['centimeter', 'centimeters', 'centimetre', 'centimetres', 'cm'] },
      { id: 'millimeter', name: 'Millimeter', symbol: 'mm', category: 'length', factor: 0.001, system: 'metric', aliases: ['millimeter', 'millimeters', 'millimetre', 'millimetres', 'mm'] },
      { id: 'micrometer', name: 'Micrometer', symbol: 'µm', category: 'length', factor: 1e-6, system: 'metric', aliases: ['micrometer', 'micrometers', 'micron', 'microns', 'µm', 'um'] },
      { id: 'nanometer', name: 'Nanometer', symbol: 'nm', category: 'length', factor: 1e-9, system: 'metric', aliases: ['nanometer', 'nanometers', 'nm'] },
      { id: 'picometer', name: 'Picometer', symbol: 'pm', category: 'length', factor: 1e-12, system: 'metric', aliases: ['picometer', 'picometers', 'pm'] },
      { id: 'angstrom', name: 'Angstrom', symbol: 'Å', category: 'length', factor: 1e-10, system: 'other', aliases: ['angstrom', 'angstroms', 'å', 'a'] },
      { id: 'mile', name: 'Mile', symbol: 'mi', category: 'length', factor: 1609.344, system: 'imperial', aliases: ['mile', 'miles', 'mi'] },
      { id: 'yard', name: 'Yard', symbol: 'yd', category: 'length', factor: 0.9144, system: 'imperial', aliases: ['yard', 'yards', 'yd', 'yds'] },
      { id: 'foot', name: 'Foot', symbol: 'ft', category: 'length', factor: 0.3048, system: 'imperial', aliases: ['foot', 'feet', 'ft', "'"] },
      { id: 'inch', name: 'Inch', symbol: 'in', category: 'length', factor: 0.0254, system: 'imperial', aliases: ['inch', 'inches', 'in', '"'] },
      { id: 'nautical_mile', name: 'Nautical Mile', symbol: 'nmi', category: 'length', factor: 1852, system: 'nautical', aliases: ['nautical mile', 'nautical miles', 'nmi', 'nm'] },
      { id: 'light_year', name: 'Light Year', symbol: 'ly', category: 'length', factor: 9.4607304725808e15, system: 'astronomical', aliases: ['light year', 'light years', 'ly'] },
      { id: 'astronomical_unit', name: 'Astronomical Unit', symbol: 'AU', category: 'length', factor: 149597870700, system: 'astronomical', aliases: ['astronomical unit', 'au', 'AU'] },
      { id: 'parsec', name: 'Parsec', symbol: 'pc', category: 'length', factor: 3.08567758149137e16, system: 'astronomical', aliases: ['parsec', 'parsecs', 'pc'] },
      { id: 'fathom', name: 'Fathom', symbol: 'fath', category: 'length', factor: 1.8288, system: 'nautical', aliases: ['fathom', 'fathoms'] },
      { id: 'rod', name: 'Rod / Pole', symbol: 'rd', category: 'length', factor: 5.0292, system: 'imperial', aliases: ['rod', 'rods', 'pole', 'poles', 'rd'] },
      { id: 'furlong', name: 'Furlong', symbol: 'fur', category: 'length', factor: 201.168, system: 'imperial', aliases: ['furlong', 'furlongs', 'fur'] },
      { id: 'thou', name: 'Thou / Mil', symbol: 'mil', category: 'length', factor: 0.0000254, system: 'imperial', aliases: ['thou', 'mil', 'mils'] },
    ],
  },
  {
    id: 'mass',
    name: 'Mass & Weight',
    group: 'Basic',
    iconName: 'Weight',
    description: 'Convert between kilograms, grams, pounds, ounces, tons, stones, and carats.',
    baseUnitId: 'kilogram',
    popularPairs: [
      ['kilogram', 'pound'],
      ['gram', 'ounce'],
      ['pound', 'ounce'],
      ['metric_ton', 'short_ton'],
      ['stone', 'kilogram'],
    ],
    units: [
      { id: 'kilogram', name: 'Kilogram', symbol: 'kg', category: 'mass', factor: 1, baseUnit: true, system: 'si', aliases: ['kilogram', 'kilograms', 'kg', 'kgs', 'kilo', 'kilos'] },
      { id: 'gram', name: 'Gram', symbol: 'g', category: 'mass', factor: 0.001, system: 'metric', aliases: ['gram', 'grams', 'g', 'gm'] },
      { id: 'milligram', name: 'Milligram', symbol: 'mg', category: 'mass', factor: 1e-6, system: 'metric', aliases: ['milligram', 'milligrams', 'mg'] },
      { id: 'microgram', name: 'Microgram', symbol: 'µg', category: 'mass', factor: 1e-9, system: 'metric', aliases: ['microgram', 'micrograms', 'mcg', 'µg', 'ug'] },
      { id: 'metric_ton', name: 'Metric Ton (Tonne)', symbol: 't', category: 'mass', factor: 1000, system: 'metric', aliases: ['tonne', 'tonnes', 'metric ton', 'metric tons', 't'] },
      { id: 'pound', name: 'Pound', symbol: 'lb', category: 'mass', factor: 0.45359237, system: 'imperial', aliases: ['pound', 'pounds', 'lb', 'lbs', '#'] },
      { id: 'ounce', name: 'Ounce', symbol: 'oz', category: 'mass', factor: 0.028349523125, system: 'imperial', aliases: ['ounce', 'ounces', 'oz'] },
      { id: 'stone', name: 'Stone', symbol: 'st', category: 'mass', factor: 6.35029318, system: 'imperial', aliases: ['stone', 'stones', 'st'] },
      { id: 'short_ton', name: 'US Short Ton', symbol: 'ton (US)', category: 'mass', factor: 907.18474, system: 'us_customary', aliases: ['short ton', 'us ton', 'ton'] },
      { id: 'long_ton', name: 'Imperial Long Ton', symbol: 'ton (UK)', category: 'mass', factor: 1016.0469088, system: 'imperial', aliases: ['long ton', 'imperial ton', 'uk ton'] },
      { id: 'carat', name: 'Carat (Metric)', symbol: 'ct', category: 'mass', factor: 0.0002, system: 'other', aliases: ['carat', 'carats', 'ct'] },
      { id: 'grain', name: 'Grain', symbol: 'gr', category: 'mass', factor: 0.00006479891, system: 'imperial', aliases: ['grain', 'grains', 'gr'] },
      { id: 'slug', name: 'Slug', symbol: 'slug', category: 'mass', factor: 14.593903, system: 'imperial', aliases: ['slug', 'slugs'] },
      { id: 'troy_ounce', name: 'Troy Ounce', symbol: 'oz t', category: 'mass', factor: 0.0311034768, system: 'other', aliases: ['troy ounce', 'troy ounces', 'oz t', 'ozt'] },
    ],
  },
  {
    id: 'area',
    name: 'Area',
    group: 'Basic',
    iconName: 'Square',
    description: 'Convert between square meters, square feet, acres, hectares, and square kilometers.',
    baseUnitId: 'square_meter',
    popularPairs: [
      ['square_meter', 'square_foot'],
      ['hectare', 'acre'],
      ['square_kilometer', 'square_mile'],
      ['square_foot', 'square_inch'],
    ],
    units: [
      { id: 'square_meter', name: 'Square Meter', symbol: 'm²', category: 'area', factor: 1, baseUnit: true, system: 'si', aliases: ['sq m', 'square meter', 'm2', 'm^2', 'sq meter'] },
      { id: 'square_kilometer', name: 'Square Kilometer', symbol: 'km²', category: 'area', factor: 1e6, system: 'metric', aliases: ['sq km', 'square kilometer', 'km2', 'km^2'] },
      { id: 'square_centimeter', name: 'Square Centimeter', symbol: 'cm²', category: 'area', factor: 1e-4, system: 'metric', aliases: ['sq cm', 'square centimeter', 'cm2', 'cm^2'] },
      { id: 'square_millimeter', name: 'Square Millimeter', symbol: 'mm²', category: 'area', factor: 1e-6, system: 'metric', aliases: ['sq mm', 'square millimeter', 'mm2', 'mm^2'] },
      { id: 'hectare', name: 'Hectare', symbol: 'ha', category: 'area', factor: 10000, system: 'metric', aliases: ['hectare', 'hectares', 'ha'] },
      { id: 'acre', name: 'Acre', symbol: 'ac', category: 'area', factor: 4046.8564224, system: 'imperial', aliases: ['acre', 'acres', 'ac'] },
      { id: 'square_mile', name: 'Square Mile', symbol: 'mi²', category: 'area', factor: 2589988.110336, system: 'imperial', aliases: ['sq mi', 'square mile', 'mi2', 'mi^2'] },
      { id: 'square_yard', name: 'Square Yard', symbol: 'yd²', category: 'area', factor: 0.83612736, system: 'imperial', aliases: ['sq yd', 'square yard', 'yd2', 'yd^2'] },
      { id: 'square_foot', name: 'Square Foot', symbol: 'ft²', category: 'area', factor: 0.09290304, system: 'imperial', aliases: ['sq ft', 'square foot', 'ft2', 'ft^2', 'sq feet'] },
      { id: 'square_inch', name: 'Square Inch', symbol: 'in²', category: 'area', factor: 0.00064516, system: 'imperial', aliases: ['sq in', 'square inch', 'in2', 'in^2'] },
      { id: 'are', name: 'Are', symbol: 'a', category: 'area', factor: 100, system: 'metric', aliases: ['are', 'ares', 'a'] },
      { id: 'barn', name: 'Barn', symbol: 'b', category: 'area', factor: 1e-28, system: 'other', aliases: ['barn', 'barns', 'b'] },
    ],
  },
  {
    id: 'volume',
    name: 'Volume & Capacity',
    group: 'Basic',
    iconName: 'Box',
    description: 'Convert between liters, milliliters, gallons, cubic meters, cups, fluid ounces, and barrels.',
    baseUnitId: 'liter',
    popularPairs: [
      ['liter', 'us_gallon'],
      ['milliliter', 'us_fluid_ounce'],
      ['us_cup', 'milliliter'],
      ['cubic_meter', 'cubic_foot'],
      ['us_gallon', 'imperial_gallon'],
    ],
    units: [
      { id: 'liter', name: 'Liter', symbol: 'L', category: 'volume', factor: 1, baseUnit: true, system: 'si', aliases: ['liter', 'liters', 'litre', 'litres', 'l', 'L'] },
      { id: 'milliliter', name: 'Milliliter', symbol: 'mL', category: 'volume', factor: 0.001, system: 'metric', aliases: ['milliliter', 'milliliters', 'ml', 'mL', 'cc'] },
      { id: 'cubic_meter', name: 'Cubic Meter', symbol: 'm³', category: 'volume', factor: 1000, system: 'si', aliases: ['cubic meter', 'm3', 'm^3', 'cu m'] },
      { id: 'cubic_centimeter', name: 'Cubic Centimeter', symbol: 'cm³', category: 'volume', factor: 0.001, system: 'metric', aliases: ['cubic centimeter', 'cm3', 'cm^3', 'cc'] },
      { id: 'us_gallon', name: 'US Liquid Gallon', symbol: 'gal (US)', category: 'volume', factor: 3.785411784, system: 'us_customary', aliases: ['us gallon', 'gallon', 'gal', 'gallons'] },
      { id: 'us_quart', name: 'US Quart', symbol: 'qt (US)', category: 'volume', factor: 0.946352946, system: 'us_customary', aliases: ['us quart', 'quart', 'qt'] },
      { id: 'us_pint', name: 'US Pint', symbol: 'pt (US)', category: 'volume', factor: 0.473176473, system: 'us_customary', aliases: ['us pint', 'pint', 'pt'] },
      { id: 'us_cup', name: 'US Cup', symbol: 'cup (US)', category: 'volume', factor: 0.24, system: 'us_customary', aliases: ['us cup', 'cup', 'cups'] },
      { id: 'us_fluid_ounce', name: 'US Fluid Ounce', symbol: 'fl oz (US)', category: 'volume', factor: 0.0295735295625, system: 'us_customary', aliases: ['us fluid ounce', 'fl oz', 'fluid ounce', 'floz'] },
      { id: 'us_tablespoon', name: 'US Tablespoon', symbol: 'tbsp (US)', category: 'volume', factor: 0.01478676478125, system: 'us_customary', aliases: ['us tablespoon', 'tbsp', 'tablespoon'] },
      { id: 'us_teaspoon', name: 'US Teaspoon', symbol: 'tsp (US)', category: 'volume', factor: 0.00492892159375, system: 'us_customary', aliases: ['us teaspoon', 'tsp', 'teaspoon'] },
      { id: 'imperial_gallon', name: 'Imperial Gallon (UK)', symbol: 'gal (UK)', category: 'volume', factor: 4.54609, system: 'imperial', aliases: ['imperial gallon', 'uk gallon', 'gal uk'] },
      { id: 'imperial_quart', name: 'Imperial Quart (UK)', symbol: 'qt (UK)', category: 'volume', factor: 1.1365225, system: 'imperial', aliases: ['imperial quart', 'uk quart'] },
      { id: 'imperial_pint', name: 'Imperial Pint (UK)', symbol: 'pt (UK)', category: 'volume', factor: 0.56826125, system: 'imperial', aliases: ['imperial pint', 'uk pint'] },
      { id: 'imperial_fluid_ounce', name: 'Imperial Fluid Ounce', symbol: 'fl oz (UK)', category: 'volume', factor: 0.0284130625, system: 'imperial', aliases: ['imperial fluid ounce', 'uk fl oz'] },
      { id: 'cubic_foot', name: 'Cubic Foot', symbol: 'ft³', category: 'volume', factor: 28.316846592, system: 'imperial', aliases: ['cubic foot', 'ft3', 'ft^3', 'cu ft', 'cft'] },
      { id: 'cubic_inch', name: 'Cubic Inch', symbol: 'in³', category: 'volume', factor: 0.016387064, system: 'imperial', aliases: ['cubic inch', 'in3', 'in^3', 'cu in'] },
      { id: 'cubic_yard', name: 'Cubic Yard', symbol: 'yd³', category: 'volume', factor: 764.554857984, system: 'imperial', aliases: ['cubic yard', 'yd3', 'yd^3', 'cu yd'] },
      { id: 'oil_barrel', name: 'Oil Barrel (bbl)', symbol: 'bbl', category: 'volume', factor: 158.987294928, system: 'other', aliases: ['oil barrel', 'barrel', 'bbl'] },
    ],
  },
  {
    id: 'temperature',
    name: 'Temperature',
    group: 'Basic',
    iconName: 'Thermometer',
    description: 'Convert between Celsius, Fahrenheit, Kelvin, Rankine, Delisle, Newton, and Réaumur scales.',
    baseUnitId: 'celsius',
    popularPairs: [
      ['celsius', 'fahrenheit'],
      ['celsius', 'kelvin'],
      ['fahrenheit', 'kelvin'],
      ['rankine', 'fahrenheit'],
    ],
    units: [
      {
        id: 'celsius',
        name: 'Celsius',
        symbol: '°C',
        category: 'temperature',
        baseUnit: true,
        factor: 1,
        system: 'metric',
        aliases: ['celsius', 'centigrade', 'c', '°c', 'deg c'],
      },
      {
        id: 'fahrenheit',
        name: 'Fahrenheit',
        symbol: '°F',
        category: 'temperature',
        system: 'imperial',
        aliases: ['fahrenheit', 'f', '°f', 'deg f'],
        customFromUnit: (f) => (Number(f) - 32) * (5 / 9),
        customToUnit: (c) => Number(c) * (9 / 5) + 32,
      },
      {
        id: 'kelvin',
        name: 'Kelvin',
        symbol: 'K',
        category: 'temperature',
        system: 'si',
        aliases: ['kelvin', 'k', 'deg k'],
        customFromUnit: (k) => Number(k) - 273.15,
        customToUnit: (c) => Number(c) + 273.15,
      },
      {
        id: 'rankine',
        name: 'Rankine',
        symbol: '°R',
        category: 'temperature',
        system: 'imperial',
        aliases: ['rankine', 'r', '°r', 'deg r'],
        customFromUnit: (r) => (Number(r) - 491.67) * (5 / 9),
        customToUnit: (c) => (Number(c) + 273.15) * (9 / 5),
      },
      {
        id: 'delisle',
        name: 'Delisle',
        symbol: '°De',
        category: 'temperature',
        system: 'other',
        aliases: ['delisle', 'de', '°de'],
        customFromUnit: (d) => 100 - Number(d) * (2 / 3),
        customToUnit: (c) => (100 - Number(c)) * (3 / 2),
      },
      {
        id: 'newton',
        name: 'Newton',
        symbol: '°N',
        category: 'temperature',
        system: 'other',
        aliases: ['newton', 'deg n', '°n'],
        customFromUnit: (n) => Number(n) * (100 / 33),
        customToUnit: (c) => Number(c) * (33 / 100),
      },
      {
        id: 'reaumur',
        name: 'Réaumur',
        symbol: '°Ré',
        category: 'temperature',
        system: 'other',
        aliases: ['reaumur', 'réaumur', 're', '°re', '°ré'],
        customFromUnit: (r) => Number(r) * (5 / 4),
        customToUnit: (c) => Number(c) * (4 / 5),
      },
      {
        id: 'romer',
        name: 'Rømer',
        symbol: '°Rø',
        category: 'temperature',
        system: 'other',
        aliases: ['romer', 'rømer', 'ro', '°ro', '°rø'],
        customFromUnit: (ro) => (Number(ro) - 7.5) * (40 / 21),
        customToUnit: (c) => Number(c) * (21 / 40) + 7.5,
      },
    ],
  },
  {
    id: 'time',
    name: 'Time',
    group: 'Basic',
    iconName: 'Clock',
    description: 'Convert between seconds, minutes, hours, days, weeks, months, years, and decades.',
    baseUnitId: 'second',
    popularPairs: [
      ['minute', 'second'],
      ['hour', 'minute'],
      ['day', 'hour'],
      ['year', 'day'],
      ['millisecond', 'second'],
    ],
    units: [
      { id: 'second', name: 'Second', symbol: 's', category: 'time', factor: 1, baseUnit: true, system: 'si', aliases: ['second', 'seconds', 's', 'sec', 'secs'] },
      { id: 'millisecond', name: 'Millisecond', symbol: 'ms', category: 'time', factor: 1e-3, system: 'metric', aliases: ['millisecond', 'milliseconds', 'ms'] },
      { id: 'microsecond', name: 'Microsecond', symbol: 'µs', category: 'time', factor: 1e-6, system: 'metric', aliases: ['microsecond', 'microseconds', 'µs', 'us'] },
      { id: 'nanosecond', name: 'Nanosecond', symbol: 'ns', category: 'time', factor: 1e-9, system: 'metric', aliases: ['nanosecond', 'nanoseconds', 'ns'] },
      { id: 'picosecond', name: 'Picosecond', symbol: 'ps', category: 'time', factor: 1e-12, system: 'metric', aliases: ['picosecond', 'picoseconds', 'ps'] },
      { id: 'minute', name: 'Minute', symbol: 'min', category: 'time', factor: 60, system: 'metric', aliases: ['minute', 'minutes', 'min', 'mins'] },
      { id: 'hour', name: 'Hour', symbol: 'h', category: 'time', factor: 3600, system: 'metric', aliases: ['hour', 'hours', 'h', 'hr', 'hrs'] },
      { id: 'day', name: 'Day', symbol: 'd', category: 'time', factor: 86400, system: 'metric', aliases: ['day', 'days', 'd'] },
      { id: 'week', name: 'Week', symbol: 'wk', category: 'time', factor: 604800, system: 'metric', aliases: ['week', 'weeks', 'wk', 'wks'] },
      { id: 'month', name: 'Month (Average)', symbol: 'mo', category: 'time', factor: 2629800, system: 'metric', aliases: ['month', 'months', 'mo'] }, // 30.4375 days
      { id: 'year', name: 'Year (Julian 365.25d)', symbol: 'yr', category: 'time', factor: 31557600, system: 'metric', aliases: ['year', 'years', 'yr', 'yrs'] },
      { id: 'decade', name: 'Decade', symbol: 'dec', category: 'time', factor: 315576000, system: 'other', aliases: ['decade', 'decades'] },
      { id: 'century', name: 'Century', symbol: 'c.', category: 'time', factor: 3155760000, system: 'other', aliases: ['century', 'centuries'] },
      { id: 'millennium', name: 'Millennium', symbol: 'mill.', category: 'time', factor: 31557600000, system: 'other', aliases: ['millennium', 'millennia'] },
    ],
  },
  {
    id: 'speed',
    name: 'Speed & Velocity',
    group: 'Basic',
    iconName: 'Gauge',
    description: 'Convert between km/h, mph, m/s, knots, Mach, and speed of light.',
    baseUnitId: 'meter_per_second',
    popularPairs: [
      ['kilometer_per_hour', 'mile_per_hour'],
      ['meter_per_second', 'kilometer_per_hour'],
      ['knot', 'kilometer_per_hour'],
      ['mile_per_hour', 'knot'],
    ],
    units: [
      { id: 'meter_per_second', name: 'Meter per second', symbol: 'm/s', category: 'speed', factor: 1, baseUnit: true, system: 'si', aliases: ['m/s', 'mps', 'meter per second'] },
      { id: 'kilometer_per_hour', name: 'Kilometer per hour', symbol: 'km/h', category: 'speed', factor: 1 / 3.6, system: 'metric', aliases: ['km/h', 'kph', 'kmh', 'kilometer per hour'] },
      { id: 'mile_per_hour', name: 'Mile per hour', symbol: 'mph', category: 'speed', factor: 0.44704, system: 'imperial', aliases: ['mph', 'mi/h', 'mile per hour', 'miles per hour'] },
      { id: 'knot', name: 'Knot (Nautical mi/h)', symbol: 'kn', category: 'speed', factor: 1852 / 3600, system: 'nautical', aliases: ['knot', 'knots', 'kn', 'kt'] },
      { id: 'foot_per_second', name: 'Foot per second', symbol: 'ft/s', category: 'speed', factor: 0.3048, system: 'imperial', aliases: ['ft/s', 'fps', 'foot per second'] },
      { id: 'mach', name: 'Mach (ISA Sea Level)', symbol: 'M', category: 'speed', factor: 340.29, system: 'other', aliases: ['mach', 'm'] },
      { id: 'speed_of_light', name: 'Speed of Light (c)', symbol: 'c', category: 'speed', factor: 299792458, system: 'other', aliases: ['speed of light', 'c'] },
    ],
  },
  {
    id: 'pace',
    name: 'Running & Cycling Pace',
    group: 'Basic',
    iconName: 'Timer',
    description: 'Convert between running and swimming pace (min/km, min/mile, sec/100m, etc.).',
    baseUnitId: 'second_per_meter',
    popularPairs: [
      ['minute_per_kilometer', 'minute_per_mile'],
      ['second_per_kilometer', 'second_per_mile'],
      ['second_per_100m', 'minute_per_kilometer'],
    ],
    units: [
      { id: 'second_per_meter', name: 'Second per meter', symbol: 's/m', category: 'pace', factor: 1, baseUnit: true, system: 'si', aliases: ['s/m', 'sec/m'] },
      {
        id: 'minute_per_kilometer',
        name: 'Minutes per kilometer',
        symbol: 'min/km',
        category: 'pace',
        system: 'metric',
        aliases: ['min/km', 'min per km', 'minutes/km'],
        customFromUnit: (val) => (Number(val) * 60) / 1000,
        customToUnit: (val) => (Number(val) * 1000) / 60,
      },
      {
        id: 'minute_per_mile',
        name: 'Minutes per mile',
        symbol: 'min/mi',
        category: 'pace',
        system: 'imperial',
        aliases: ['min/mi', 'min/mile', 'minutes/mile', 'min per mile'],
        customFromUnit: (val) => (Number(val) * 60) / 1609.344,
        customToUnit: (val) => (Number(val) * 1609.344) / 60,
      },
      {
        id: 'second_per_kilometer',
        name: 'Seconds per kilometer',
        symbol: 's/km',
        category: 'pace',
        system: 'metric',
        aliases: ['s/km', 'sec/km'],
        customFromUnit: (val) => Number(val) / 1000,
        customToUnit: (val) => Number(val) * 1000,
      },
      {
        id: 'second_per_mile',
        name: 'Seconds per mile',
        symbol: 's/mi',
        category: 'pace',
        system: 'imperial',
        aliases: ['s/mi', 'sec/mi', 'sec/mile'],
        customFromUnit: (val) => Number(val) / 1609.344,
        customToUnit: (val) => Number(val) * 1609.344,
      },
      {
        id: 'second_per_100m',
        name: 'Seconds per 100m (Swim Pace)',
        symbol: 's/100m',
        category: 'pace',
        system: 'metric',
        aliases: ['s/100m', 'swim pace', 'sec/100m'],
        customFromUnit: (val) => Number(val) / 100,
        customToUnit: (val) => Number(val) * 100,
      },
    ],
  },
];
