import { CategoryDefinition } from '../engine/types';

export const electricalCategories: CategoryDefinition[] = [
  {
    id: 'current',
    name: 'Electric Current',
    group: 'Electrical',
    iconName: 'Zap',
    description: 'Convert between Amperes, milliamperes, microamperes, kiloamperes, and abamperes.',
    baseUnitId: 'ampere',
    popularPairs: [
      ['ampere', 'milliampere'],
      ['milliampere', 'microampere'],
      ['kiloampere', 'ampere'],
    ],
    units: [
      { id: 'ampere', name: 'Ampere', symbol: 'A', category: 'current', factor: 1, baseUnit: true, system: 'si', aliases: ['ampere', 'amperes', 'amp', 'amps', 'a', 'A'] },
      { id: 'milliampere', name: 'Milliampere', symbol: 'mA', category: 'current', factor: 1e-3, system: 'metric', aliases: ['milliampere', 'ma', 'mA', 'milliamp'] },
      { id: 'microampere', name: 'Microampere', symbol: 'µA', category: 'current', factor: 1e-6, system: 'metric', aliases: ['microampere', 'ua', 'µa', 'µA'] },
      { id: 'kiloampere', name: 'Kiloampere', symbol: 'kA', category: 'current', factor: 1e3, system: 'metric', aliases: ['kiloampere', 'ka', 'kA'] },
      { id: 'abampere', name: 'Abampere (Biot)', symbol: 'abA', category: 'current', factor: 10, system: 'cgs', aliases: ['abampere', 'aba', 'biot'] },
    ],
  },
  {
    id: 'voltage',
    name: 'Electric Potential & Voltage',
    group: 'Electrical',
    iconName: 'Cpu',
    description: 'Convert between Volts, millivolts, microvolts, kilovolts, and megavolts.',
    baseUnitId: 'volt',
    popularPairs: [
      ['volt', 'millivolt'],
      ['kilovolt', 'volt'],
      ['millivolt', 'microvolt'],
    ],
    units: [
      { id: 'volt', name: 'Volt', symbol: 'V', category: 'voltage', factor: 1, baseUnit: true, system: 'si', aliases: ['volt', 'volts', 'v', 'V'] },
      { id: 'millivolt', name: 'Millivolt', symbol: 'mV', category: 'voltage', factor: 1e-3, system: 'metric', aliases: ['millivolt', 'mv', 'mV'] },
      { id: 'microvolt', name: 'Microvolt', symbol: 'µV', category: 'voltage', factor: 1e-6, system: 'metric', aliases: ['microvolt', 'uv', 'µv', 'µV'] },
      { id: 'kilovolt', name: 'Kilovolt', symbol: 'kV', category: 'voltage', factor: 1e3, system: 'metric', aliases: ['kilovolt', 'kv', 'kV'] },
      { id: 'megavolt', name: 'Megavolt', symbol: 'MV', category: 'voltage', factor: 1e6, system: 'metric', aliases: ['megavolt', 'mv', 'MV'] },
      { id: 'statvolt', name: 'Statvolt', symbol: 'statV', category: 'voltage', factor: 299.792458, system: 'cgs', aliases: ['statvolt', 'statv'] },
    ],
  },
  {
    id: 'resistance',
    name: 'Electrical Resistance',
    group: 'Electrical',
    iconName: 'Unplug',
    description: 'Convert between Ohms, milliohms, kilohms, megohms, and gigaohms.',
    baseUnitId: 'ohm',
    popularPairs: [
      ['kilohm', 'ohm'],
      ['megohm', 'kilohm'],
      ['ohm', 'milliohm'],
    ],
    units: [
      { id: 'ohm', name: 'Ohm', symbol: 'Ω', category: 'resistance', factor: 1, baseUnit: true, system: 'si', aliases: ['ohm', 'ohms', 'ω', 'r'] },
      { id: 'milliohm', name: 'Milliohm', symbol: 'mΩ', category: 'resistance', factor: 1e-3, system: 'metric', aliases: ['milliohm', 'mohm', 'mω'] },
      { id: 'kilohm', name: 'Kilohm', symbol: 'kΩ', category: 'resistance', factor: 1e3, system: 'metric', aliases: ['kilohm', 'kohm', 'k', 'kω'] },
      { id: 'megohm', name: 'Megohm', symbol: 'MΩ', category: 'resistance', factor: 1e6, system: 'metric', aliases: ['megohm', 'mohm', 'm', 'mω'] },
      { id: 'gigaohm', name: 'Gigaohm', symbol: 'GΩ', category: 'resistance', factor: 1e9, system: 'metric', aliases: ['gigaohm', 'gohm', 'gω'] },
    ],
  },
  {
    id: 'conductance',
    name: 'Electrical Conductance',
    group: 'Electrical',
    iconName: 'Share2',
    description: 'Convert between Siemens, millisiemens, microsiemens, and Mhos.',
    baseUnitId: 'siemens',
    popularPairs: [
      ['siemens', 'millisiemens'],
      ['siemens', 'mho'],
    ],
    units: [
      { id: 'siemens', name: 'Siemens', symbol: 'S', category: 'conductance', factor: 1, baseUnit: true, system: 'si', aliases: ['siemens', 's', 'S'] },
      { id: 'millisiemens', name: 'Millisiemens', symbol: 'mS', category: 'conductance', factor: 1e-3, system: 'metric', aliases: ['millisiemens', 'ms', 'mS'] },
      { id: 'microsiemens', name: 'Microsiemens', symbol: 'µS', category: 'conductance', factor: 1e-6, system: 'metric', aliases: ['microsiemens', 'us', 'µs', 'µS'] },
      { id: 'mho', name: 'Mho (Reciprocal Ohm)', symbol: '℧', category: 'conductance', factor: 1, system: 'other', aliases: ['mho', 'mhos'] },
    ],
  },
  {
    id: 'capacitance',
    name: 'Capacitance',
    group: 'Electrical',
    iconName: 'Radio',
    description: 'Convert between Farads, millifarads, microfarads, nanofarads, and picofarads.',
    baseUnitId: 'farad',
    popularPairs: [
      ['microfarad', 'nanofarad'],
      ['nanofarad', 'picofarad'],
      ['farad', 'microfarad'],
    ],
    units: [
      { id: 'farad', name: 'Farad', symbol: 'F', category: 'capacitance', factor: 1, baseUnit: true, system: 'si', aliases: ['farad', 'farads', 'f', 'F'] },
      { id: 'millifarad', name: 'Millifarad', symbol: 'mF', category: 'capacitance', factor: 1e-3, system: 'metric', aliases: ['millifarad', 'mf', 'mF'] },
      { id: 'microfarad', name: 'Microfarad', symbol: 'µF', category: 'capacitance', factor: 1e-6, system: 'metric', aliases: ['microfarad', 'uf', 'µf', 'uF', 'µF'] },
      { id: 'nanofarad', name: 'Nanofarad', symbol: 'nF', category: 'capacitance', factor: 1e-9, system: 'metric', aliases: ['nanofarad', 'nf', 'nF'] },
      { id: 'picofarad', name: 'Picofarad', symbol: 'pF', category: 'capacitance', factor: 1e-12, system: 'metric', aliases: ['picofarad', 'pf', 'pF'] },
    ],
  },
  {
    id: 'inductance',
    name: 'Inductance',
    group: 'Electrical',
    iconName: 'Repeat',
    description: 'Convert between Henrys, millihenrys, microhenrys, and nanohenrys.',
    baseUnitId: 'henry',
    popularPairs: [
      ['henry', 'millihenry'],
      ['millihenry', 'microhenry'],
    ],
    units: [
      { id: 'henry', name: 'Henry', symbol: 'H', category: 'inductance', factor: 1, baseUnit: true, system: 'si', aliases: ['henry', 'henrys', 'h', 'H'] },
      { id: 'millihenry', name: 'Millihenry', symbol: 'mH', category: 'inductance', factor: 1e-3, system: 'metric', aliases: ['millihenry', 'mh', 'mH'] },
      { id: 'microhenry', name: 'Microhenry', symbol: 'µH', category: 'inductance', factor: 1e-6, system: 'metric', aliases: ['microhenry', 'uh', 'µh', 'µH'] },
      { id: 'nanohenry', name: 'Nanohenry', symbol: 'nH', category: 'inductance', factor: 1e-9, system: 'metric', aliases: ['nanohenry', 'nh', 'nH'] },
    ],
  },
  {
    id: 'electric_charge',
    name: 'Electric Charge',
    group: 'Electrical',
    iconName: 'BatteryCharging',
    description: 'Convert between Coulombs, Ampere-hours, milliampere-hours (mAh), and elementary charges.',
    baseUnitId: 'coulomb',
    popularPairs: [
      ['ampere_hour', 'milliampere_hour'],
      ['coulomb', 'milliampere_hour'],
      ['coulomb', 'elementary_charge'],
    ],
    units: [
      { id: 'coulomb', name: 'Coulomb', symbol: 'C', category: 'electric_charge', factor: 1, baseUnit: true, system: 'si', aliases: ['coulomb', 'coulombs', 'c', 'C'] },
      { id: 'millicoulomb', name: 'Millicoulomb', symbol: 'mC', category: 'electric_charge', factor: 1e-3, system: 'metric', aliases: ['millicoulomb', 'mc', 'mC'] },
      { id: 'microcoulomb', name: 'Microcoulomb', symbol: 'µC', category: 'electric_charge', factor: 1e-6, system: 'metric', aliases: ['microcoulomb', 'uc', 'µc', 'µC'] },
      { id: 'ampere_hour', name: 'Ampere-hour', symbol: 'Ah', category: 'electric_charge', factor: 3600, system: 'other', aliases: ['ampere hour', 'ah', 'Ah'] },
      { id: 'milliampere_hour', name: 'Milliampere-hour', symbol: 'mAh', category: 'electric_charge', factor: 3.6, system: 'other', aliases: ['milliampere hour', 'mah', 'mAh'] },
      { id: 'elementary_charge', name: 'Elementary Charge (e)', symbol: 'e', category: 'electric_charge', factor: 1.602176634e-19, system: 'si', aliases: ['elementary charge', 'e'] },
      { id: 'faraday', name: 'Faraday (chemical)', symbol: 'F', category: 'electric_charge', factor: 96485.33212, system: 'other', aliases: ['faraday'] },
    ],
  },
];
