import { CategoryDefinition } from '../engine/types';

export const physicsCategories: CategoryDefinition[] = [
  {
    id: 'pressure',
    name: 'Pressure',
    group: 'Physics & Engineering',
    iconName: 'GaugeCircle',
    description: 'Convert between Pascal, bar, PSI, standard atmosphere, Torr, and mmHg.',
    baseUnitId: 'pascal',
    popularPairs: [
      ['bar', 'psi'],
      ['pascal', 'bar'],
      ['standard_atmosphere', 'psi'],
      ['torr', 'pascal'],
      ['kilopascal', 'psi'],
    ],
    units: [
      { id: 'pascal', name: 'Pascal', symbol: 'Pa', category: 'pressure', factor: 1, baseUnit: true, system: 'si', aliases: ['pascal', 'pascals', 'pa', 'Pa'] },
      { id: 'kilopascal', name: 'Kilopascal', symbol: 'kPa', category: 'pressure', factor: 1e3, system: 'metric', aliases: ['kilopascal', 'kpa', 'kPa'] },
      { id: 'megapascal', name: 'Megapascal', symbol: 'MPa', category: 'pressure', factor: 1e6, system: 'metric', aliases: ['megapascal', 'mpa', 'MPa'] },
      { id: 'bar', name: 'Bar', symbol: 'bar', category: 'pressure', factor: 1e5, system: 'metric', aliases: ['bar', 'bars'] },
      { id: 'millibar', name: 'Millibar', symbol: 'mbar', category: 'pressure', factor: 100, system: 'metric', aliases: ['millibar', 'mbar', 'mb'] },
      { id: 'hectopascal', name: 'Hectopascal', symbol: 'hPa', category: 'pressure', factor: 100, system: 'metric', aliases: ['hectopascal', 'hpa', 'hPa'] },
      { id: 'standard_atmosphere', name: 'Standard Atmosphere', symbol: 'atm', category: 'pressure', factor: 101325, system: 'other', aliases: ['standard atmosphere', 'atm', 'atmosphere'] },
      { id: 'technical_atmosphere', name: 'Technical Atmosphere', symbol: 'at', category: 'pressure', factor: 98066.5, system: 'other', aliases: ['technical atmosphere', 'at'] },
      { id: 'psi', name: 'Pounds per Square Inch', symbol: 'psi', category: 'pressure', factor: 6894.757293168, system: 'imperial', aliases: ['psi', 'pounds per square inch', 'lbf/in2', 'lb/sq in'] },
      { id: 'torr', name: 'Torr / mmHg', symbol: 'Torr', category: 'pressure', factor: 133.32236842105, system: 'other', aliases: ['torr', 'mmhg', 'mm hg', 'millimeter of mercury'] },
      { id: 'inch_of_mercury', name: 'Inches of Mercury', symbol: 'inHg', category: 'pressure', factor: 3386.388640341, system: 'imperial', aliases: ['inhg', 'in hg', 'inch of mercury'] },
      { id: 'inch_of_water', name: 'Inches of Water', symbol: 'inH₂O', category: 'pressure', factor: 249.08891, system: 'imperial', aliases: ['inh2o', 'in h2o', 'inch of water'] },
    ],
  },
  {
    id: 'force',
    name: 'Force',
    group: 'Physics & Engineering',
    iconName: 'Weight',
    description: 'Convert between Newtons, dynes, pound-force, kilogram-force, and kips.',
    baseUnitId: 'newton',
    popularPairs: [
      ['newton', 'pound_force'],
      ['kilonewton', 'pound_force'],
      ['kilogram_force', 'newton'],
      ['dyne', 'newton'],
    ],
    units: [
      { id: 'newton', name: 'Newton', symbol: 'N', category: 'force', factor: 1, baseUnit: true, system: 'si', aliases: ['newton', 'newtons', 'n', 'N'] },
      { id: 'kilonewton', name: 'Kilonewton', symbol: 'kN', category: 'force', factor: 1e3, system: 'metric', aliases: ['kilonewton', 'kn', 'kN'] },
      { id: 'meganewton', name: 'Meganewton', symbol: 'MN', category: 'force', factor: 1e6, system: 'metric', aliases: ['meganewton', 'mn', 'MN'] },
      { id: 'dyne', name: 'Dyne', symbol: 'dyn', category: 'force', factor: 1e-5, system: 'cgs', aliases: ['dyne', 'dynes', 'dyn'] },
      { id: 'pound_force', name: 'Pound-force', symbol: 'lbf', category: 'force', factor: 4.4482216152605, system: 'imperial', aliases: ['pound-force', 'lbf', 'pound force', 'lbs force'] },
      { id: 'kilogram_force', name: 'Kilogram-force (Kilopond)', symbol: 'kgf', category: 'force', factor: 9.80665, system: 'metric', aliases: ['kilogram-force', 'kgf', 'kilopond', 'kp'] },
      { id: 'kip', name: 'Kip (Kilopound-force)', symbol: 'kip', category: 'force', factor: 4448.2216152605, system: 'imperial', aliases: ['kip', 'kips', 'klbf'] },
      { id: 'ounce_force', name: 'Ounce-force', symbol: 'ozf', category: 'force', factor: 0.27801385095378125, system: 'imperial', aliases: ['ounce-force', 'ozf', 'oz-f'] },
    ],
  },
  {
    id: 'energy',
    name: 'Energy & Work',
    group: 'Physics & Engineering',
    iconName: 'Zap',
    description: 'Convert between Joules, calories, kilowatt-hours, electronvolts, and BTUs.',
    baseUnitId: 'joule',
    popularPairs: [
      ['joule', 'calorie'],
      ['kilowatt_hour', 'joule'],
      ['kilocalorie', 'kilojoule'],
      ['btu', 'joule'],
      ['electronvolt', 'joule'],
    ],
    units: [
      { id: 'joule', name: 'Joule', symbol: 'J', category: 'energy', factor: 1, baseUnit: true, system: 'si', aliases: ['joule', 'joules', 'j', 'J'] },
      { id: 'kilojoule', name: 'Kilojoule', symbol: 'kJ', category: 'energy', factor: 1e3, system: 'metric', aliases: ['kilojoule', 'kj', 'kJ'] },
      { id: 'megajoule', name: 'Megajoule', symbol: 'MJ', category: 'energy', factor: 1e6, system: 'metric', aliases: ['megajoule', 'mj', 'MJ'] },
      { id: 'gigajoule', name: 'Gigajoule', symbol: 'GJ', category: 'energy', factor: 1e9, system: 'metric', aliases: ['gigajoule', 'gj', 'GJ'] },
      { id: 'calorie', name: 'Calorie (Thermochemical)', symbol: 'cal', category: 'energy', factor: 4.184, system: 'metric', aliases: ['calorie', 'calories', 'cal'] },
      { id: 'kilocalorie', name: 'Kilocalorie (Food Calorie)', symbol: 'kcal / Cal', category: 'energy', factor: 4184, system: 'metric', aliases: ['kilocalorie', 'kcal', 'food calorie', 'cal'] },
      { id: 'watt_hour', name: 'Watt-hour', symbol: 'Wh', category: 'energy', factor: 3600, system: 'metric', aliases: ['watt-hour', 'wh', 'Wh'] },
      { id: 'kilowatt_hour', name: 'Kilowatt-hour', symbol: 'kWh', category: 'energy', factor: 3.6e6, system: 'metric', aliases: ['kilowatt-hour', 'kwh', 'kWh'] },
      { id: 'megawatt_hour', name: 'Megawatt-hour', symbol: 'MWh', category: 'energy', factor: 3.6e9, system: 'metric', aliases: ['megawatt-hour', 'mwh', 'MWh'] },
      { id: 'electronvolt', name: 'Electronvolt', symbol: 'eV', category: 'energy', factor: 1.602176634e-19, system: 'si', aliases: ['electronvolt', 'ev', 'eV'] },
      { id: 'btu', name: 'British Thermal Unit (ISO)', symbol: 'BTU', category: 'energy', factor: 1055.056, system: 'imperial', aliases: ['btu', 'btus', 'british thermal unit'] },
      { id: 'therm', name: 'Therm (US)', symbol: 'thm', category: 'energy', factor: 105480400, system: 'us_customary', aliases: ['therm', 'therms', 'thm'] },
      { id: 'foot_pound', name: 'Foot-pound force', symbol: 'ft·lbf', category: 'energy', factor: 1.3558179483314004, system: 'imperial', aliases: ['foot-pound', 'ft-lb', 'ft lbf'] },
      { id: 'erg', name: 'Erg', symbol: 'erg', category: 'energy', factor: 1e-7, system: 'cgs', aliases: ['erg', 'ergs'] },
    ],
  },
  {
    id: 'power',
    name: 'Power',
    group: 'Physics & Engineering',
    iconName: 'Flame',
    description: 'Convert between Watts, kilowatts, horsepower, BTU/hour, and tons of refrigeration.',
    baseUnitId: 'watt',
    popularPairs: [
      ['kilowatt', 'horsepower_metric'],
      ['watt', 'horsepower_imperial'],
      ['kilowatt', 'btu_per_hour'],
      ['megawatt', 'kilowatt'],
    ],
    units: [
      { id: 'watt', name: 'Watt', symbol: 'W', category: 'power', factor: 1, baseUnit: true, system: 'si', aliases: ['watt', 'watts', 'w', 'W'] },
      { id: 'kilowatt', name: 'Kilowatt', symbol: 'kW', category: 'power', factor: 1e3, system: 'metric', aliases: ['kilowatt', 'kw', 'kW'] },
      { id: 'megawatt', name: 'Megawatt', symbol: 'MW', category: 'power', factor: 1e6, system: 'metric', aliases: ['megawatt', 'mw', 'MW'] },
      { id: 'gigawatt', name: 'Gigawatt', symbol: 'GW', category: 'power', factor: 1e9, system: 'metric', aliases: ['gigawatt', 'gw', 'GW'] },
      { id: 'horsepower_metric', name: 'Horsepower (Metric PS/CV)', symbol: 'PS', category: 'power', factor: 735.49875, system: 'metric', aliases: ['metric horsepower', 'ps', 'cv', 'pk'] },
      { id: 'horsepower_imperial', name: 'Horsepower (Mechanical hp)', symbol: 'hp(I)', category: 'power', factor: 745.6998715822702, system: 'imperial', aliases: ['horsepower', 'hp', 'bhp', 'mechanical horsepower'] },
      { id: 'horsepower_electrical', name: 'Horsepower (Electrical)', symbol: 'hp(E)', category: 'power', factor: 746, system: 'other', aliases: ['electrical horsepower', 'hp e'] },
      { id: 'btu_per_hour', name: 'BTU per hour', symbol: 'BTU/h', category: 'power', factor: 0.29307107, system: 'imperial', aliases: ['btu/h', 'btu per hour', 'btuh'] },
      { id: 'ton_refrigeration', name: 'Ton of Refrigeration', symbol: 'TR', category: 'power', factor: 3516.85284, system: 'us_customary', aliases: ['ton of refrigeration', 'tr', 'tons of refrigeration'] },
      { id: 'foot_pound_per_minute', name: 'Foot-pound per minute', symbol: 'ft·lbf/min', category: 'power', factor: 0.02259696580552334, system: 'imperial', aliases: ['ft-lb/min', 'ft lbf/min'] },
    ],
  },
  {
    id: 'torque',
    name: 'Torque',
    group: 'Physics & Engineering',
    iconName: 'RotateCcw',
    description: 'Convert between Newton-meters, pound-feet, pound-inches, and kilogram-force meters.',
    baseUnitId: 'newton_meter',
    popularPairs: [
      ['newton_meter', 'pound_foot'],
      ['pound_foot', 'pound_inch'],
      ['kilogram_force_meter', 'newton_meter'],
    ],
    units: [
      { id: 'newton_meter', name: 'Newton-meter', symbol: 'N·m', category: 'torque', factor: 1, baseUnit: true, system: 'si', aliases: ['newton meter', 'nm', 'N.m', 'n-m'] },
      { id: 'kilonewton_meter', name: 'Kilonewton-meter', symbol: 'kN·m', category: 'torque', factor: 1e3, system: 'metric', aliases: ['kilonewton meter', 'knm', 'kN.m'] },
      { id: 'pound_foot', name: 'Pound-foot', symbol: 'lbf·ft', category: 'torque', factor: 1.3558179483314004, system: 'imperial', aliases: ['pound-foot', 'lb-ft', 'ft-lb', 'lbf ft', 'foot pound'] },
      { id: 'pound_inch', name: 'Pound-inch', symbol: 'lbf·in', category: 'torque', factor: 0.1129848290276167, system: 'imperial', aliases: ['pound-inch', 'lb-in', 'in-lb', 'inch pound'] },
      { id: 'kilogram_force_meter', name: 'Kilogram-force meter', symbol: 'kgf·m', category: 'torque', factor: 9.80665, system: 'metric', aliases: ['kgf-m', 'kgfm', 'kilogram meter'] },
      { id: 'dyne_centimeter', name: 'Dyne-centimeter', symbol: 'dyn·cm', category: 'torque', factor: 1e-7, system: 'cgs', aliases: ['dyne centimeter', 'dyn cm'] },
    ],
  },
  {
    id: 'acceleration',
    name: 'Acceleration',
    group: 'Physics & Engineering',
    iconName: 'TrendingUp',
    description: 'Convert between m/s², standard gravity (g-force), ft/s², and Gals.',
    baseUnitId: 'meter_per_square_second',
    popularPairs: [
      ['meter_per_square_second', 'standard_gravity'],
      ['foot_per_square_second', 'meter_per_square_second'],
    ],
    units: [
      { id: 'meter_per_square_second', name: 'Meter per square second', symbol: 'm/s²', category: 'acceleration', factor: 1, baseUnit: true, system: 'si', aliases: ['m/s2', 'm/s^2', 'mps2'] },
      { id: 'standard_gravity', name: 'Standard Gravity (g-force)', symbol: 'g₀', category: 'acceleration', factor: 9.80665, system: 'other', aliases: ['g', 'g-force', 'standard gravity', 'g0'] },
      { id: 'foot_per_square_second', name: 'Foot per square second', symbol: 'ft/s²', category: 'acceleration', factor: 0.3048, system: 'imperial', aliases: ['ft/s2', 'ft/s^2', 'fps2'] },
      { id: 'gal', name: 'Gal (cm/s²)', symbol: 'Gal', category: 'acceleration', factor: 0.01, system: 'cgs', aliases: ['gal', 'cm/s2'] },
    ],
  },
  {
    id: 'density',
    name: 'Density',
    group: 'Physics & Engineering',
    iconName: 'Layers',
    description: 'Convert between kg/m³, g/cm³, lb/ft³, lb/in³, and lb/gal.',
    baseUnitId: 'kilogram_per_cubic_meter',
    popularPairs: [
      ['kilogram_per_cubic_meter', 'gram_per_cubic_centimeter'],
      ['gram_per_cubic_centimeter', 'pound_per_cubic_foot'],
    ],
    units: [
      { id: 'kilogram_per_cubic_meter', name: 'Kilogram per cubic meter', symbol: 'kg/m³', category: 'density', factor: 1, baseUnit: true, system: 'si', aliases: ['kg/m3', 'kg/m^3', 'kg per cu m'] },
      { id: 'gram_per_cubic_centimeter', name: 'Gram per cubic centimeter', symbol: 'g/cm³', category: 'density', factor: 1000, system: 'metric', aliases: ['g/cm3', 'g/cc', 'g/ml'] },
      { id: 'pound_per_cubic_foot', name: 'Pound per cubic foot', symbol: 'lb/ft³', category: 'density', factor: 16.01846337396, system: 'imperial', aliases: ['lb/ft3', 'pcf', 'lb per cu ft'] },
      { id: 'pound_per_cubic_inch', name: 'Pound per cubic inch', symbol: 'lb/in³', category: 'density', factor: 27679.90471019, system: 'imperial', aliases: ['lb/in3', 'pci'] },
      { id: 'pound_per_gallon_us', name: 'Pound per US Gallon', symbol: 'lb/gal (US)', category: 'density', factor: 119.8264273169, system: 'us_customary', aliases: ['lb/gal', 'ppg'] },
    ],
  },
  {
    id: 'frequency',
    name: 'Frequency',
    group: 'Physics & Engineering',
    iconName: 'Activity',
    description: 'Convert between Hertz, kHz, MHz, GHz, RPM, and radians per second.',
    baseUnitId: 'hertz',
    popularPairs: [
      ['hertz', 'megahertz'],
      ['gigahertz', 'megahertz'],
      ['revolutions_per_minute', 'hertz'],
    ],
    units: [
      { id: 'hertz', name: 'Hertz', symbol: 'Hz', category: 'frequency', factor: 1, baseUnit: true, system: 'si', aliases: ['hertz', 'hz', 'Hz'] },
      { id: 'kilohertz', name: 'Kilohertz', symbol: 'kHz', category: 'frequency', factor: 1e3, system: 'metric', aliases: ['kilohertz', 'khz', 'kHz'] },
      { id: 'megahertz', name: 'Megahertz', symbol: 'MHz', category: 'frequency', factor: 1e6, system: 'metric', aliases: ['megahertz', 'mhz', 'MHz'] },
      { id: 'gigahertz', name: 'Gigahertz', symbol: 'GHz', category: 'frequency', factor: 1e9, system: 'metric', aliases: ['gigahertz', 'ghz', 'GHz'] },
      { id: 'terahertz', name: 'Terahertz', symbol: 'THz', category: 'frequency', factor: 1e12, system: 'metric', aliases: ['terahertz', 'thz', 'THz'] },
      { id: 'revolutions_per_minute', name: 'Revolutions per minute (RPM)', symbol: 'RPM', category: 'frequency', factor: 1 / 60, system: 'other', aliases: ['rpm', 'RPM', 'rev/min'] },
      { id: 'radian_per_second', name: 'Radian per second', symbol: 'rad/s', category: 'frequency', factor: 1 / (2 * Math.PI), system: 'si', aliases: ['rad/s', 'rad/sec'] },
    ],
  },
  {
    id: 'flow_rate',
    name: 'Flow Rate (Volume)',
    group: 'Physics & Engineering',
    iconName: 'Droplets',
    description: 'Convert between L/s, L/min, m³/h, GPM (gallons per minute), and CFM.',
    baseUnitId: 'cubic_meter_per_second',
    popularPairs: [
      ['liter_per_minute', 'us_gallon_per_minute'],
      ['cubic_meter_per_hour', 'liter_per_second'],
      ['cubic_foot_per_minute', 'liter_per_second'],
    ],
    units: [
      { id: 'cubic_meter_per_second', name: 'Cubic meter per second', symbol: 'm³/s', category: 'flow_rate', factor: 1, baseUnit: true, system: 'si', aliases: ['m3/s', 'cms'] },
      { id: 'liter_per_second', name: 'Liter per second', symbol: 'L/s', category: 'flow_rate', factor: 0.001, system: 'metric', aliases: ['l/s', 'lps', 'liter/s'] },
      { id: 'liter_per_minute', name: 'Liter per minute', symbol: 'L/min', category: 'flow_rate', factor: 1 / 60000, system: 'metric', aliases: ['l/min', 'lpm'] },
      { id: 'liter_per_hour', name: 'Liter per hour', symbol: 'L/h', category: 'flow_rate', factor: 1 / 3600000, system: 'metric', aliases: ['l/h', 'lph'] },
      { id: 'cubic_meter_per_hour', name: 'Cubic meter per hour', symbol: 'm³/h', category: 'flow_rate', factor: 1 / 3600, system: 'metric', aliases: ['m3/h', 'cmh'] },
      { id: 'us_gallon_per_minute', name: 'US Gallon per minute (GPM)', symbol: 'GPM', category: 'flow_rate', factor: 6.30901964e-5, system: 'us_customary', aliases: ['gpm', 'gal/min'] },
      { id: 'us_gallon_per_hour', name: 'US Gallon per hour (GPH)', symbol: 'GPH', category: 'flow_rate', factor: 1.0515032733333e-6, system: 'us_customary', aliases: ['gph', 'gal/h'] },
      { id: 'cubic_foot_per_minute', name: 'Cubic foot per minute (CFM)', symbol: 'CFM', category: 'flow_rate', factor: 0.0004719474432, system: 'imperial', aliases: ['cfm', 'ft3/min'] },
    ],
  },
  {
    id: 'viscosity',
    name: 'Viscosity (Dynamic & Kinematic)',
    group: 'Physics & Engineering',
    iconName: 'Pipette',
    description: 'Convert between Pascal-second, Poise, Centipoise, Stoke, and Centistoke.',
    baseUnitId: 'pascal_second',
    popularPairs: [
      ['pascal_second', 'centipoise'],
      ['poise', 'centipoise'],
    ],
    units: [
      { id: 'pascal_second', name: 'Pascal-second (Dynamic)', symbol: 'Pa·s', category: 'viscosity', factor: 1, baseUnit: true, system: 'si', aliases: ['pa*s', 'pascal second', 'pa.s'] },
      { id: 'poise', name: 'Poise (Dynamic)', symbol: 'P', category: 'viscosity', factor: 0.1, system: 'cgs', aliases: ['poise', 'p'] },
      { id: 'centipoise', name: 'Centipoise (Dynamic)', symbol: 'cP', category: 'viscosity', factor: 0.001, system: 'cgs', aliases: ['centipoise', 'cp', 'cP'] },
      { id: 'pound_force_second_per_sq_ft', name: 'lbf·s/ft² (Dynamic)', symbol: 'lbf·s/ft²', category: 'viscosity', factor: 47.880258980336, system: 'imperial', aliases: ['lbf s/ft2', 'slug/(ft-s)'] },
    ],
  },
  {
    id: 'angle',
    name: 'Angle',
    group: 'Physics & Engineering',
    iconName: 'Compass',
    description: 'Convert between Degrees, Radians, Gradians, Arcminutes, Arcseconds, and Turns.',
    baseUnitId: 'radian',
    popularPairs: [
      ['degree', 'radian'],
      ['degree', 'gradian'],
      ['turn', 'degree'],
      ['arcminute', 'degree'],
    ],
    units: [
      { id: 'radian', name: 'Radian', symbol: 'rad', category: 'angle', factor: 1, baseUnit: true, system: 'si', aliases: ['radian', 'radians', 'rad'] },
      { id: 'degree', name: 'Degree', symbol: '°', category: 'angle', factor: Math.PI / 180, system: 'other', aliases: ['degree', 'degrees', 'deg', '°'] },
      { id: 'gradian', name: 'Gradian (Gon)', symbol: 'grad', category: 'angle', factor: Math.PI / 200, system: 'other', aliases: ['gradian', 'gradians', 'grad', 'gon'] },
      { id: 'arcminute', name: 'Arcminute', symbol: '′', category: 'angle', factor: Math.PI / 10800, system: 'other', aliases: ['arcminute', 'arcmin', "'"] },
      { id: 'arcsecond', name: 'Arcsecond', symbol: '″', category: 'angle', factor: Math.PI / 648000, system: 'other', aliases: ['arcsecond', 'arcsec', '"'] },
      { id: 'turn', name: 'Turn / Revolution', symbol: 'rev', category: 'angle', factor: 2 * Math.PI, system: 'other', aliases: ['turn', 'turns', 'rev', 'revolution'] },
      { id: 'milliradian', name: 'Milliradian', symbol: 'mrad', category: 'angle', factor: 0.001, system: 'metric', aliases: ['milliradian', 'mrad', 'mil'] },
    ],
  },
];
